### ISSUE TITLE
Redis Spark JedisDataException: ERR wrong number of arguments

### ISSUE THREAD

**Issue by Velmuruganms12** [RedisLabs/spark-redis#10]
When trying to connect to redis from spark i am getting following exception show below I am not sure i am missing here.

Code:
----------------------------------------------------------------------------------------------------------------------------------------
 val sc = new SparkContext(new SparkConf()
      .setMaster("local").setAppName(getClass.getName)
      .set("redis.host", "127.0.0.1")
      .set("redis.port", "6379")
 .set("redis.auth", "xxxx"))
    val content = fromInputStream(getClass.getClassLoader.getResourceAsStream("blog")).
      getLines.toArray.mkString("\n")

    val redisConfigStandalone = new RedisConfig(new RedisEndpoint("127.0.0.1", 6379))
   val redisConfigCluster = new RedisConfig(new RedisEndpoint("127.0.0.1", 6379))
    val wcnts = sc.parallelize(content.split("\\W+").filter(!_.isEmpty)).map((_, 1)).reduceByKey(_ + _).map(x => (x._1, x._2.toString))

    val wds = sc.parallelize(content.split("\\W+").filter(!_.isEmpty))
    println(wds.count())

Exception:
----------------------------------------------------------------------------------------------------------------------------------------

Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'info' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:142)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:207)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:196)
	at redis.clients.jedis.BinaryJedis.info(BinaryJedis.java:2671)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:127)
	at com.redislabs.provider.redis.RedisConfig.getSlots(RedisConfig.scala:204)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:159)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:89)
	at com.aline.cloudscm.util.SimpleApp2$.main(SimpleApp2.scala:21)
	at com.aline.cloudscm.util.SimpleApp2.main(SimpleApp2.scala)
16/02/28 15:33:27 INFO SparkContext: Invoking stop() from shutdown hook

**Comment by dvirsky** [comment]
sounds like you are running an old version of redis that doesn't support arguments to INFO. what version are you running?

**Comment by Velmuruganms12** [comment]
I use  Redis server version 2.4.6 (26cdd13a:0). let me try the latest version

**Comment by dvirsky** [comment]
It's recommended to work with redis >=3.0. 3.2 is coming out soon

**Comment by dvirsky** [comment]
2.4 is extremely old, about 4 years old IIRC

**Comment by Velmuruganms12** [comment]
Yes now download redis 3.0 issue got resolved i am able to connect 

thanks for the quick reply

**Comment by dvirsky** [comment]
no problem. BTW it's even documented that you should use redis >2.8 :)
