### ISSUE TITLE
Scan getCursor problem

### ISSUE THREAD

**Issue by chensi2017** [RedisLabs/spark-redis#121]
I use jedis 2.9.0 version api 
![default](https://user-images.githubusercontent.com/31915542/49786375-78c91f80-fd5e-11e8-8625-013bbc4a0ffc.png)
There are the console information
`java.lang.NoSuchMethodError: redis.clients.jedis.ScanResult.getCursor()Ljava/lang/String;
	at com.redislabs.provider.redis.rdd.Keys$class.com$redislabs$provider$redis$rdd$Keys$$scanKeys(RedisRDD.scala:411)
	at com.redislabs.provider.redis.rdd.Keys$$anonfun$getKeys$1.apply(RedisRDD.scala:435)
	at com.redislabs.provider.redis.rdd.Keys$$anonfun$getKeys$1.apply(RedisRDD.scala:431)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.TraversableOnce$FlattenOps$$anon$1.hasNext(TraversableOnce.scala:464)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)`
![default](https://user-images.githubusercontent.com/31915542/49786514-102e7280-fd5f-11e8-8967-9e0bbebdd832.png)
In 2.9.0 getCursor method return String type.So in readme.md should not support 2.9.0

**Comment by chensi2017** [comment]
yeah, jedis 3.0 is OK
