### ISSUE TITLE
getting ArrayIndexOutOfBoundsException: 0 at com.redislabs....getMasterNode(RedisRDD.scala:458)

### ISSUE THREAD

**Issue by ayushvasu** [RedisLabs/spark-redis#124]
This the code I am running 
```
val sparkSession = org.apache.spark.sql.SparkSession.builder
    .config(new SparkConf()
      .setMaster("local")
      .setAppName("myApp")
      // initial redis host - can be any node in cluster mode
      .set("spark.redis.host", "172.0.10.53")
      // initial redis port
      .set("spark.redis.port", "6379")
      // optional redis AUTH password
      //.set("redis.auth", "")
    ).getOrCreate
  val path = "/home/impadmin/abc.txt"
  val base_df = sparkSession.read.option("header", "false").csv(path)
  //Store the DataSet in Redis
  base_df.write
    .format("org.apache.spark.sql.redis")
    .option("table", "temp")
    .mode(SaveMode.Overwrite)
    .save()
```

dependencies
 ```
<dependency>
            <groupId>com.redislabs</groupId>
            <artifactId>spark-redis</artifactId>
            <version>2.3.1-M3</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/redis.clients/jedis -->
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>
```
Redis cluster info

172.0.10.53:6379> info replication
role:master
connected_slaves:3
slave0:ip=172.0.10.52,port=6379,state=online,offset=17808,lag=1
slave1:ip=172.0.10.73,port=6379,state=online,offset=17808,lag=0
slave2:ip=172.0.10.75,port=6379,state=online,offset=17808,lag=1
master_replid:93e8e816f9d0cabd5a5d5cc41971a024739b15f7
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:17808
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:17808 

Stack Trace 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.redislabs.provider.redis.rdd.Keys$class.getMasterNode(RedisRDD.scala:458)
	at org.apache.spark.sql.redis.RedisSourceRelation.getMasterNode(RedisSourceRelation.scala:22)
	at org.apache.spark.sql.redis.RedisSourceRelation.saveSchema(RedisSourceRelation.scala:245)
	at org.apache.spark.sql.redis.RedisSourceRelation.insert(RedisSourceRelation.scala:119)
	at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:24)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
	at ApplicationStart$.delayedEndpoint$ApplicationStart$1(ApplicationStart.scala:26)
	at ApplicationStart$delayedInit$body.apply(ApplicationStart.scala:5)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at ApplicationStart$.main(ApplicationStart.scala:5)
	at ApplicationStart.main(ApplicationStart.scala)
```

**Comment by fe2s** [comment]
Can you please run the following code and share the output?

```
val config = new RedisConfig(RedisEndpoint(host = "172.0.10.53", port = 6379))
println(config.hosts.mkString(" "))
```

**Comment by fe2s** [comment]
Also,

How did you manage to build `2.3.1-M3` with jedis `2.9.0`, it should not compile.

**Comment by fe2s** [comment]
Correction to the previous comment - 
spark-redis has a compile dependency on jedis, so you shouldn't include it in your project dependencies.

**Comment by fe2s** [comment]
Can you please check what does `config.nodes` return?
What Redis version do you use?

**Comment by ayushvasu** [comment]
We are using 4.0.12 redis version 

`config.nodes` is also returning empty array
```
scala> val config = new RedisConfig(RedisEndpoint(host = "172.25.41.53", port = 6379))
config: com.redislabs.provider.redis.RedisConfig = com.redislabs.provider.redis.RedisConfig@378d8d1b
scala> println(config.nodes)
[Lcom.redislabs.provider.redis.RedisNode;@78e88c15
scala> println(config.nodes.size)
0
```


But when I am running,
```
scala> RedisEndpoint(host = "172.0.10.53", port = 6379).connect
res15: redis.clients.jedis.Jedis = redis.clients.jedis.Jedis@1a867210
```
I am getting Jedis object

**Comment by fe2s** [comment]
I see that you use different ip addresses
```
val config = new RedisConfig(RedisEndpoint(host = "172.25.41.53", port = 6379))
``` 
and
```
RedisEndpoint(host = "172.0.10.53", port = 6379).connect
```

Can you run the following please?

1. 
```
val config = new RedisConfig(RedisEndpoint(host = "172.0.10.53", port = 6379))
println(config.nodes.size)
```

2.
```
val clusterSlots = RedisEndpoint(host = "172.0.10.53", port = 6379).connect().clusterSlots()
println("slots = " + clusterSlots.size())
```
3.
Connect to `172.0.10.53:6379` with redis cli and run `cluster slots` command

**Comment by ayushvasu** [comment]
There was the changes in IP because I changed the cluster to new boxes.
I am seeing some problem with the setup of the cluster on old nodes

Let me fix that and will get back to you

**Comment by ayushvasu** [comment]
Issue is resolved.
Problem was there with the cluster settings

**Comment by ShirlyPeng** [comment]
Can you tell me how you resolved the problem: config.hosts.size == 0?
