### ISSUE TITLE
when partitions.number is greater than redis master host size, it may cause java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by cyq89051127** [RedisLabs/spark-redis#159]
Let's suppose we hava a redis cluster of 3 master , and when we read data from redis using sc.fromRedisKV("*",8), an exception occurs:

     java.lang.IndexOutOfBoundsException: 7
    	at scala.collection.mutable.ArraySeq.apply(ArraySeq.scala:62)
    	at com.redislabs.provider.redis.rdd.RedisKeysRDD$$anonfun$getPartitions$1.apply(RedisRDD.scala:243)
    	at com.redislabs.provider.redis.rdd.RedisKeysRDD$$anonfun$getPartitions$1.apply(RedisRDD.scala:240)
    	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    	at scala.collection.immutable.Range.foreach(Range.scala:160)
    	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    	at com.redislabs.provider.redis.rdd.RedisKeysRDD.getPartitions(RedisRDD.scala:240)
    	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
    	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
    	at scala.Option.getOrElse(Option.scala:121)
    	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
    	at com.redislabs.provider.redis.rdd.RedisKVRDD.getPartitions(RedisRDD.scala:23)
    	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
    	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
    	at scala.Option.getOrElse(Option.scala:121)
    	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
    	at org.apache.spark.rdd.OrderedRDDFunctions.sortByKey$default$2(OrderedRDDFunctions.scala:59)
    	at com.redislabs.provider.redis.rdd.RedisRddSuite$$anonfun$2.apply$mcV$sp(RedisRddSuite.scala:47)
    	at com.redislabs.provider.redis.rdd.RedisRddSuite$$anonfun$2.apply(RedisRddSuite.scala:45)
    	at com.redislabs.provider.redis.rdd.RedisRddSuite$$anonfun$2.apply(RedisRddSuite.scala:45)
    	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
    	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    	at org.scalatest.Transformer.apply(Transformer.scala:22)
    	at org.scalatest.Transformer.apply(Transformer.scala:20)
    	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
    	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
    	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
    	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
    	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
    	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
    	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
    	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
    	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
    	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    	at scala.collection.immutable.List.foreach(List.scala:392)
    	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
    	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
    	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
    	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
    	at org.scalatest.Suite$class.run(Suite.scala:1424)
    	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
    	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
    	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
    	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
    	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
    	at com.redislabs.provider.redis.rdd.cluster.RedisKeysClusterSuite.org$scalatest$BeforeAndAfterAll$$super$run(RedisKeysClusterSuite.scala:6)
    	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
    	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
    	at com.redislabs.provider.redis.rdd.cluster.RedisKeysClusterSuite.run(RedisKeysClusterSuite.scala:6)
    	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
    	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
    	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
    	at scala.collection.immutable.List.foreach(List.scala:392)
    	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
    	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
    	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
    	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
    	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
    	at org.scalatest.tools.Runner$.run(Runner.scala:883)
    	at org.scalatest.tools.Runner.run(Runner.scala)
    	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
    	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

The  root cause is in RedisKeysRDD#getPartitions mothod. In this method, when we have 3 master(master1, master 2, master3) and we assign 8 partitions, 

**there'll be two partitions on master1, two partitions on master2, three partitions on master3**, due to the code 

    val lastExtCnt = if (presExtCnt * hosts.size < partitionNum) (presExtCnt + 1) else presExtCnt

**Comment by fe2s** [comment]
Hi @cyq89051127,

Thank you for the contribution. It looks good. This method looks quite complicated, we need to add proper unit(and maybe integration) tests. I'm merging your fix and will open another ticket with a unit test request.
