### ISSUE TITLE
Failed to find data source: org.apache.spark.sql.redis

### ISSUE THREAD

**Issue by cx707662950** [RedisLabs/spark-redis#170]
when I use df to write data to redis, got the error as below:
    Failed to find data source: org.apache.spark.sql.redis

   code as below

val spark = SparkSession
      .builder()
      .appName("redis-df")
      .master("spark://bigdata1:7077")
      .config("redis.host", "10.66.36.114")
      .config("redis.port", "6379")
      .getOrCreate()

    val personSeq = Seq(Person("John", 30), Person("Peter", 45))
    val df = spark.createDataFrame(personSeq)

    df.write
      .format("org.apache.spark.sql.redis")
      .option("table", "person")
      .mode(SaveMode.Overwrite)
      .save()

spark-redis version: 2.3.0  jedis:2.9.0

**Comment by raffiot** [comment]
@cx707662950 Did you find a solution ?

**Comment by fe2s** [comment]
"Failed to find datasource" typically occurs if spark-redis is not found in driver/executor classpath.

**Comment by beatscode** [comment]
What if you get this error locally within a unit test? All the `.to` and `.from` functions work but cannot write a Dataframe to redis.

**Comment by fe2s** [comment]
@beatscode 
Could you please share the code that works and doesn't work for you, as well as exception stack trace?

**Comment by kikalyan** [comment]
I get error when trying to write a data to redis. Help is appreciated.

Error: java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.redis. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:689)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:743)
  at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:972)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:304)
  ... 59 elided
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.redis.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:72)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:663)
  at scala.util.Try$.apply(Try.scala:213)
  at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:663)
  at scala.util.Failure.orElse(Try.scala:224)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:663)
  ... 62 more


Code : 

import com.redislabs.provider.redis._
import org.apache.spark.sql.{DataFrame, SparkSession}

  val spark = SparkSession.
  builder().
  appName("myApp").
  master("local[*]").
  config("spark.redis.host", "XXXX.redis.cache.windows.net").
  config("spark.redis.port", "6380").
  config("spark.redis.auth", "XXXXX").
  getOrCreate()
  
val df = spark.sql("""SELECT * FROM sharddb.allupshardsubgroupmap_sub""")

df.write.
  format("org.apache.spark.sql.redis").
  option("table", "foo").
  save()

**Comment by edwinlebreton** [comment]
Any update on this ? I am currently facing the exact same issue
