### ISSUE TITLE
Spark Redis does not support stream reading

### ISSUE THREAD

**Issue by H-Theking** [RedisLabs/spark-redis#203]
Spark version: 2.4.4
Spark Redis version: 2.4.0
Spark Streaming: 2.4.4

scalaVersion : 2.12.1

When starting the spark application with redis connection:

`val clicks = spark
      .readStream
      .format("org.apache.spark.sql.redis")
      .option("stream.keys", "clicks")
      .schema(StructType(Array(
        StructField("asset", StringType),
        StructField("cost", LongType)
      )))
      .load()`

I get the exception

`
	Exception in thread "main" java.lang.UnsupportedOperationException: Data source org.apache.spark.sql.redis does not support streamed reading
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:247)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:95)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:95)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:33)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:215)
	at ClickAnalysis$.main(ClickAnalysis.scala:25)
	at ClickAnalysis.main(ClickAnalysis.scala)
`

**Comment by fe2s** [comment]
Hi @H-Theking ,

it should be `.format("redis")`, see https://github.com/RedisLabs/spark-redis/blob/master/doc/structured-streaming.md#structured-streaming
