### ISSUE TITLE
Jedis not honoring "spark.redis.host" configured in SparkSession builder and uses "localhost"

### ISSUE THREAD

**Issue by patrickmao93** [RedisLabs/spark-redis#213]
I initialized spark session like this

```scala
val spark = SparkSession
      .builder()
      .appName("ExtractRawTablesFromMySQL")
      .config("spark.redis.host", "my-redis.url.com")
      .config("spark.redis.port", "6379")
      .getOrCreate()
```

Later when I want to save rdd to redis

```scala
sc.toRedisSET(rdd, "tags:1")
```

But it says **"Failed connecting to host localhost:6379"**. 

Looks like it is not honoring this configuration:

```scala
.config("spark.redis.host", "my-redis.url.com")
```

Error stack:

```
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
  at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
  at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)
  at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
  at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
  at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:182)
  at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:293)
  at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:209)
  at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
  at com.redislabs.provider.redis.RedisConfig$.fromSparkConf(RedisConfig.scala:120)
  at com.redislabs.provider.redis.RedisContext.toRedisSET$default$4(redisFunctions.scala:285)
  ... 75 elided
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
  at redis.clients.jedis.Connection.connect(Connection.java:204)
  at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
  at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1862)
  at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
  at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
  at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
  ... 84 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at redis.clients.jedis.Connection.connect(Connection.java:181)
  ... 91 more
```

**Comment by fe2s** [comment]
Hi @patrickmao93 ,

I was not able to reproduce it. My code:

```scala
val spark = SparkSession
      .builder()
      .master("local[*]")
      .appName("ExtractRawTablesFromMySQL")
      .config("spark.redis.host", "my-redis.url.com")
      .config("spark.redis.port", "6379")
      .getOrCreate()


    val sc = spark.sparkContext
    val rdd = sc.parallelize(Seq("1","2"))
    sc.toRedisSET(rdd, "tags:1")
```

Getting the following as expected:
```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host my-redis.url.com:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1862)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 11 more
```

Can you please provide the full listing of your code?

**Comment by fe2s** [comment]
Please also provide the code of how `sc` value initialized.

**Comment by anoty** [comment]
Same problem，spark.master=local[*]  model is ok，but cluster model have this problem
I solved it this way
https://github.com/RedisLabs/spark-redis/blob/master/doc/cluster.md

**Comment by JDRanpariya** [comment]
I'm having the same issue, I tried with spark-redis version master, 3, 2.4 gives same Exception while connecting to redis.

**Comment by lioriner** [comment]
I'm having the same issue. 
`from pyspark.sql import SparkSession, functions as func, types

session = SparkSession.builder \
    .config("spark.redis.host", "172.31.16.223") \
    .config("spark.redis.port", "16480") \
    .config("spark.redis.auth", "pass") \
    .getOrCreate()

df = session.read.format("org.apache.spark.sql.redis") \
    .option("keys.pattern", "*") \
    .option("infer.schema", True) \
    .load()
`

and getting the error:
`An error was encountered:
An error occurred while calling o183.load.
: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:193)
	at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:317)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:233)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
	at org.apache.spark.sql.redis.RedisSourceRelation.<init>(RedisSourceRelation.scala:34)
	at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:13)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1894)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 26 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	... 33 more

Traceback (most recent call last):
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o183.load.
: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:193)
	at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:317)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:233)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
	at org.apache.spark.sql.redis.RedisSourceRelation.<init>(RedisSourceRelation.scala:34)
	at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:13)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1894)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 26 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	... 33 more`

**Comment by lioriner** [comment]
I'm having the same issue:

```
from pyspark.sql import SparkSession, functions as func, types

session = SparkSession.builder \
    .config("spark.redis.host", "172.31.16.223") \
    .config("spark.redis.port", "16480") \
    .config("spark.redis.auth", "LongPassw0rdSinceRedisCanServeOver150kAuthRequestsEverySecond") \
    .getOrCreate()

df = session.read.format("org.apache.spark.sql.redis") \
    .option("keys.pattern", "*") \
    .option("infer.schema", True) \
    .load()
```

and getting the error:
```
An error was encountered:
An error occurred while calling o183.load.
: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:193)
	at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:317)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:233)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
	at org.apache.spark.sql.redis.RedisSourceRelation.<init>(RedisSourceRelation.scala:34)
	at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:13)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1894)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 26 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	... 33 more

Traceback (most recent call last):
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/mnt/yarn/usercache/livy/appcache/application_1689594991610_0004/container_1689594991610_0004_01_000001/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o183.load.
: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:193)
	at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:317)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:233)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
	at org.apache.spark.sql.redis.RedisSourceRelation.<init>(RedisSourceRelation.scala:34)
	at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:13)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1894)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 26 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	... 33 more

```
