### ISSUE TITLE
ERR data connection don't process admin command.

### ISSUE THREAD

**Issue by songzhiyong** [RedisLabs/spark-redis#280]
I got this error, how to fix it ?

````
redis.clients.jedis.exceptions.JedisDataException: ERR data connection don't process admin command.
  at redis.clients.jedis.Protocol.processError(Protocol.java:132)
  at redis.clients.jedis.Protocol.process(Protocol.java:166)
  at redis.clients.jedis.Protocol.read(Protocol.java:220)
  at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
  at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:255)
  at redis.clients.jedis.Connection.getBulkReply(Connection.java:245)
  at redis.clients.jedis.BinaryJedis.info(BinaryJedis.java:2972)
  at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:197)
  at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:320)
  at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:236)
  at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:135)
  at org.apache.spark.sql.redis.RedisSourceRelation.<init>(RedisSourceRelation.scala:34)
  at org.apache.spark.sql.redis.DefaultSource.createRelation(DefaultSource.scala:13)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
  ... 52 elided
````

**Comment by fe2s** [comment]
Hi @songzhiyong ,
it fails while executing [INFO command](https://redis.io/commands/info). Could you try to connect to the server with the same credentials and try to execute `INFO`?

**Comment by songzhiyong** [comment]
@fe2s yes, INFO command got this error. How can I avoid this error?

**Comment by fe2s** [comment]
You can try to ask in https://github.com/redis/redis
