### ISSUE TITLE
Can't run with aws ElasticCache

### ISSUE THREAD

**Issue by gustavo-momente** [RedisLabs/spark-redis#46]
Hello, after setting up `spark-redis` I can't get it to work with AWS ElasticCache, but everything run fines using a local Redis. I get the following exception:

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
        at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
        at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
        at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
        at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
        at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
        at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:89)
        at com.redislabs.provider.redis.RedisContext.toRedisKV$default$3(redisFunctions.scala:225)
```

**Comment by mnarrell** [comment]
Any update here?

**Comment by shaynativ** [comment]
Hi, Just tested with ElastiCache and it works fine.
You probably have an access problem.
Make sure you can access EC from the machine you run Spark on.
Check the AWS security groups and VPCs.
When you are able to run redis-cli from the Spark machine to the EC endpoint the spark-redis connector would work as well.

**Comment by ronl** [comment]
Any assistance on running from ETL Glue and Spark would be appreciated?   Unable to connect to the Redis  cache.  See notes regarding that Redis Cache is configured to only be accessed from EC2s.  Not sure if that is my problem.  I have the security group opened up for anyone to access.

**Comment by blait** [comment]
I have same issue 
test 1 : local redis, local spark -> fine
test 2 : elasticache redis , emr redis-cli -> fine 
test3 : elasticache redis , emr spark -> problem......same exaption

**Comment by arturzangiev** [comment]
Did anyone succeeded to connect from local machine? I have VPN connected to AWS VPC and i can connect to Elasticache via redis-cli. However, once it come to spark-redis can't connect. It is stack at stage 1 and get timeout.
