### ISSUE TITLE
Can not load data from redis cluster, but can load data from Standalone 

### ISSUE THREAD

**Issue by vc60er** [RedisLabs/spark-redis#58]
I use spark-redis in java project, and found it can load data from standalone redis, but can not do that from redis cluster?

why?  thanks.

code as below

      SparkConf sparkConf = new SparkConf().setAppName(appname)
                .set("redis.host", "10.11.44.99") 
                .set("redis.port", "7777");
      JavaSparkContext jsc = new JavaSparkContext(sparkConf);
      Dataset<Row> ds = snapshot_redis_data(jsc.sc(), sparkConf, new Time(0));

    public static Dataset<Row> snapshot_redis_data(SparkContext sc, SparkConf conf, Time ts) {
        println("snapshot_redis_data: "
         + " redis.host=" + conf.get("redis.host")
         + " redis.port=" + conf.get("redis.port"));

        RedisConfig rCfg = new RedisConfig(new RedisEndpoint(conf));
        RedisContext rCtx = new RedisContext(sc);

        SparkSession spark = JavaSparkSessionSingleton.getInstance(conf);

        RDD<Tuple2<String, String>> kvRdd = rCtx.fromRedisKV("track.*", 5, rCfg);

        JavaRDD<Row> userRDD = kvRdd.toJavaRDD().map(new Function<Tuple2<String, String>, Row>() {
            public Row call(Tuple2<String, String> tuple2) throws Exception {
                logger.info(tuple2._1 + ":" + tuple2._2);
                String key = tuple2._1;
                String value = tuple2._2;

                String[] ss = key.split("\\.");

                return RowFactory.create(new Timestamp(ts.milliseconds()),
                        Long.parseLong(ss[2]),
                        Long.parseLong(ss[3]),
                        Long.parseLong(value));
            }
        });

        List<StructField> structFields = new ArrayList<StructField>();
        structFields.add(DataTypes.createStructField("ts", DataTypes.TimestampType, true));
        structFields.add(DataTypes.createStructField("rt", DataTypes.LongType, true));
        structFields.add(DataTypes.createStructField("item_id", DataTypes.LongType, true));
        structFields.add(DataTypes.createStructField("count", DataTypes.LongType, true));
        StructType structType = DataTypes.createStructType(structFields);

        Dataset<Row> ds = spark.createDataFrame(userRDD, structType);
        return ds;
    }

17/10/10 00:21:03 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
	at com.redislabs.provider.redis.rdd.Keys$$anonfun$getKeys$1.apply(RedisRDD.scala:417)
	at com.redislabs.provider.redis.rdd.Keys$$anonfun$getKeys$1.apply(RedisRDD.scala:416)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.redislabs.provider.redis.rdd.Keys$class.getKeys(RedisRDD.scala:416)
	at com.redislabs.provider.redis.rdd.RedisKeysRDD.getKeys(RedisRDD.scala:189)
	at com.redislabs.provider.redis.rdd.RedisKeysRDD.compute(RedisRDD.scala:271)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at com.redislabs.provider.redis.rdd.RedisKVRDD.compute(RedisRDD.scala:30)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.Connection.connect(Connection.java:155)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1643)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 37 more

**Comment by vc60er** [comment]
problems found, the configuration of my redis-cluster is wrong, not spark-redis caused

**Comment by vc60er** [comment]
Please close the issue, thanks you very much

**Comment by cheninitial** [comment]
> Please close the issue, thanks you very much
I have the same problem.
Could you tell me which configuration you fix?

thank you

**Comment by Lihengwannafly** [comment]
> > Please close the issue, thanks you very much
> > I have the same problem.
> > Could you tell me which configuration you fix?
> 
> thank you

Did you fix your problem?
